Fix typo
charlypro1/hyperblogg pull request #1
Opened 2024-03-05 19:32 UTC by charlypro1

2024-03-05 19:45 UTC, LechugacarlosE requested changes
En vez de usar tildes usa entidades HTML

2024-03-05 19:51 UTC, LechugacarlosE requested changes
En vez de usar tildes directas usa entidades HTML

2024-03-05 20:14 UTC, charlypro1 commented
Cambios hechos, por favor hazme el merge

2024-03-05 20:22 UTC, LechugacarlosE approved these changes
Excelente. Eso era!!

2024-03-05 20:25 UTC, merged

2024-03-06 18:09 UTC, charlypro1 reviewed
Ok